### ISSUE TITLE
Variable to set IE supporting versions

### ISSUE THREAD

**Issue by seleckis** [jackbrewer/stylus-mixins#12]
It would be great to add variable to set IE version to support. E.g. I don't need < IE9, so opacity mixin will generate waste for me.

**Comment by jackbrewer** [comment]
The opacity mixin will only add extra styles if you specify support for IE8 or earlier. I can see the documentation for the opacity mixin doesn't mention this, so will make a note to update it.

The extra IE specific styles only appear if you choose to set the [IE specific variables](https://github.com/jackbrewer/stylus-mixins/blob/master/docs/ie.md#default-variables) for a particular stylesheet.

Tests illustrating this are here:
- [No extra styles output (this is the default)](https://github.com/jackbrewer/stylus-mixins/blob/master/test/tests/opacity.styl#L3-L20)
- [Extra IE styles (because variables are set)](https://github.com/jackbrewer/stylus-mixins/blob/master/test/tests/opacity.styl#L23-L46)

This means you should have no waste in your generated CSS.

**Comment by jackbrewer** [comment]
[Opacity documentation updated](https://github.com/jackbrewer/stylus-mixins/blob/master/docs/opacity.md). Closing this issue. Hope this helps.

**Comment by seleckis** [comment]
I have missed that variables. Good job.
